apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ms
  namespace: devx
  labels:
    role: customer-ms
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: customer-ms
  template:
    metadata:
      labels:
        role: customer-ms
    spec:
      containers:
        - name: customer-ms
          image: public.ecr.aws/p4r4w8l8/customer-svc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
