apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapp
  namespace: devx
  labels:
    role: customerapp
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: customerapp
  template:
    metadata:
      labels:
        role: customerapp
    spec:
      containers:
        - name: customerapp
          image: public.ecr.aws/p4r4w8l8/customer-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
